### ISSUE TITLE
深入理解JVM(3) 勘误

### ISSUE THREAD

**Issue by LinXiaoTao** [CrowHawk/CrowHawk.github.io#1]
> 它是一个单线程收集器，但“单线程”并非指该收集器只会使用一个CPU或一条收集线程去完成垃圾收集工作，更重要的是它在进行垃圾收集时，必须暂停其他所有的工作线程，直至Serial收集器收集结束为止（“Stop The World”）

这句话正确意思应该是，Serial 作为单线程收集器，不仅意味着只使用单线程去执行 GC，更重要的是它在进行垃圾收集时，必须暂停其他所有的工作线程，直至Serial收集器收集结束为止（“Stop The World”）

**Comment by CrowHawk** [comment]
感谢您的不吝赐教，已改正
